#서버 포트 설정
#확장자 : 프로퍼티
#server.port=8000

#인코딩 UFT-8설정
#server.servlet.encoding.charset= UTF-8
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force=true
#server.servlet.encoding.force-request=true
#server.servlet.encoding.force-response=true
#server.tomcat.uri-encoding=UTF-8

#뷰리졸버 설정
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp 확장자 : 프로퍼티

#확장자 :yml
# 인코딩 UTF-8설정
server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    #db 연결 설정, 및 뷰리졸버 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/springboot_song?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: root
    #mapper 설정
  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 604686589310-p4gq6jn30v5gkp8iaoe0v8qjsbqi3eq1.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: 8rzsKkjL3gwl3BY6jyqu
            client-secret: URMH_OLkee
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri:  https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            
mybatis:
  mapper-locations:
  - /mappers/*.xml
      
file:
  path: C:song/workspace4/git/springboot-study/upload/
      
